# Generated by Django 5.0.4 on 2024-05-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='active',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='updated_date',
        ),
    ]
